version: "3.1"

services:
  maria :
#    image: docker.io/bitnami/mariadb:10.6
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3307:3306
    volumes:
      - ./docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ./docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=maria
      - MARIADB_USER=admin
      - MARIADB_DATABASE=maria
      - MARIADB_PASSWORD=maria
    networks:
      - backend
    restart: always

networks:
  backend: