spring:
  application:
    name: "myform"

  datasource:
    url: jdbc:mariadb://localhost:3307/maria
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
#    password: maria
    password: ENC(yjqanDMXGdI+ShLKnQVShA==)
    name: maria

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show_sql: true

  logging.level:
    org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 2
    provider-name: BC
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64
    property:
      prefix: ENC(
      suffix: )

