spring:
  application:
    name: "myform"

  datasource:
    url: jdbc:mariadb://localhost:3307/maria
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: maria
    name: maria

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show_sql: true

  logging.level:
    org.hibernate.SQL: debug

