spring:
  application:
    name: "myform"

  datasource:
    url: jdbc:mariadb://localhost:3306/maria
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: maira

    jpa:
    database: mariadb
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show_sql: true

  logging.level:
    org.hibernate.SQL: debug

